tango_with_django_project/rango/urls.py
from django.urls import path
from rango import views
from django.contrib.auth import views as auth_views

app_name = 'rango'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>/', views.show_category,
         name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('restricted/', views.restricted, name='restricted'),
    path('logout/', views.user_logout, name='logout'),
    path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
]

tango_with_django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rango import views

urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    # The above maps any URLs starting with rango/ to be handled by rango.
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tango_with_django_project/rango/models.py
# Import the Category model
from rango.models import Category
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)
    # Links UserProfile to a User instance (one-to-one)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Additional fields for the profile
    website = models.URLField(blank=True)  # Optional personal website
    picture = models.ImageField(upload_to='profile_images', blank=True)  # Profile picture

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)
    
class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

def __str__(self):
    return self.title

tango_with_django_project/rango/forms.py
from django import forms
from rango.models import Page, Category
from django.contrib.auth.models import User
from rango import views

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,
                           help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Category
        fields = ('name',)

    def clean_name(self):
        name = self.cleaned_data.get('name', '').strip()
        if not name:
            raise forms.ValidationError("Category name cannot be empty!")
        if Category.objects.filter(name__iexact=name).exists():
            raise forms.ValidationError("This category already exists!")
        return name

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['maxlength'] = Category._meta.get_field('name').max_length

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
                            help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200,
                         help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        # Provide an association between the ModelForm and a model
        model = Page
        # What fields do we want to include in our form?
        # This way we don't need every field in the model present.
        # Some fields may allow NULL values; we may not want to include them.
        # Here, we are hiding the foreign key.
        # we can either exclude the category field from the form,
        exclude = ('category',)
        # or specify the fields to include (don't include the category field).
        fields = ('title', 'url', 'views')

    def clean_url(self):
        url = self.cleaned_data.get('url')
        if url and not url.startswith(('http://', 'https://')):
            url = f'http://{url}'
        return url

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        # If url is not empty and doesn't start with 'http://',
        # then prepend 'http://'.
        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url
            
        return cleaned_data
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())  # Hide password input

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

tango_with_django_project/rango/views.py
from django.shortcuts import render, redirect, get_object_or_404
from rango.models import Category, Page
from django.http import HttpResponse
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm
from django.urls import reverse
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from datetime import datetime
from rango.utils import visitor_cookie_handler

def index(request):
    # Query the database for a list of ALL categories currently stored.
    # Order the categories by the number of likes in descending order.
    # Retrieve the top 5 only -- or all if less than 5.
    # Place the list in our context_dict dictionary (with our boldmessage!)
    # that will be passed to the template engine.
    request.session.set_test_cookie()
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    
    context_dict = {
        'boldmessage': 'Crunchy, creamy, cookie, candy, cupcake!',
        'categories': category_list,
        'pages': page_list
    }
    context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
    context_dict['categories'] = category_list

    # Call the session-based cookie handler
    visitor_cookie_handler(request)
    return render(request, 'rango/index.html')

    # Retrieve visits count from session and add to context
    context_dict['visits'] = request.session['visits']

    # Obtain the response object
    response = render(request, 'rango/index.html', context=context_dict)

    # Call the helper function to update cookies
    visitor_cookie_handler(request, response)

    # Update the context with the visit count from cookies
    context_dict['visits'] = int(request.COOKIES.get('visits', '1'))

    # Return the response with updated cookies
    return response

    # Render the response and send it back!
    return render(request, 'rango/index.html', context=context_dict)

def about(request):

    visitor_cookie_handler(request)  # Ensure visits are tracked

    visits = request.session.get('visits', 1)  # Get visit count from session
    context_dict = {'visits': visits}

    return HttpResponse("Rango says here is the about page. <br><a href='/rango/'>Back to Index</a>")
    return render(request, 'rango/about.html')

    if request.session.test_cookie_worked():
        print("TEST COOKIE WORKED!")
        request.session.delete_test_cookie()
    
    print("Request Method:", request.method)
    print("User:", request.user)

    return render(request, 'rango/about.html', {})

def show_category(request, category_name_slug):
    context_dict = {}
    category = get_object_or_404(Category, slug=category_name_slug)
    pages = Page.objects.filter(category=category)

    try:
        category = Category.objects.get(slug=category_name_slug)
        context_dict['category'] = category

        pages = Page.objects.filter(category=category)
        context_dict['pages'] = pages

    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None

    return render(request, 'rango/category.html', {'category': category, 'pages': pages})

@login_required
def add_category(request):
    form = CategoryForm()

    # A HTTP POST?
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        # Have we been provided with a valid form?
        return redirect(reverse('rango:index'))
        if form.is_valid():
            # Save the new category to the database.
            cat = form.save(commit=True)
            # Now that the category is saved, we could confirm this.
            # For now, just redirect the user back to the index view.
            return redirect(reverse('rango:index'))
        else:
            # The supplied form contained errors -
            # just print them to the terminal.
            print(form.errors)
            form = CategoryForm()

    # Will handle the bad form, new form, or no form supplied cases.
    # Render the form with error messages (if any).
    return render(request, 'rango/add_category.html', {'form': form})

def add_page(request, category_name_slug):
    category = get_object_or_404(Category, slug=category_name_slug)

    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            page = form.save(commit=False)
            page.category = category
            page.save()
            return redirect('show_category', category_name_slug=category.slug)
    else:
        form = PageForm()

    return render(request, 'rango/add_page.html', {'form': form, 'category': category})

    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

        # Redirect if category does not exist
    if category is None:
        return redirect(reverse('rango:index'))

    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return redirect(reverse('rango:show_category',
                                        kwargs={'category_name_slug': category_name_slug}))
        else:
            print(form.errors)

    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context=context_dict)


def register(request):
    registered = False  # Track registration success

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST, request.FILES)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)  # Hash the password
            user.save()

            # Create user profile but don't save yet
            profile = profile_form.save(commit=False)
            profile.user = user  # Link to User instance

            # Save profile picture if uploaded
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()  # Save UserProfile

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'rango/register.html', {
        'user_form': user_form,
        'profile_form': profile_form,
        'registered': registered
    })
def user_login(request):
    if request.method == 'POST':
        # Get username and password from form
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Authenticate user
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('rango:index'))  # Redirect to homepage
            else:
                return HttpResponse("Your Rango account is disabled.")
        else:
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")

    # Display login form if request is GET
    return render(request, 'rango/login.html')

@login_required
def restricted(request):
    return render(request, 'rango/restricted.html')
    return HttpResponse("Since you're logged in, you can see this text!")


@login_required
def add_page(request, category_name_slug):
    category = get_object_or_404(Category, slug=category_name_slug)

    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            page = form.save(commit=False)
            page.category = category
            page.save()
            return redirect(reverse('show_category', kwargs={'category_name_slug': category.slug}))
    else:
        form = PageForm()

    return render(request, 'rango/add_page.html', {'form': form, 'category': category})

@login_required
def user_logout(request):
    """Logs out the user and redirects them to the homepage."""
    logout(request)
    return redirect(reverse('rango:index'))  # Redirect to homepage

def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

def visitor_cookie_handler(request):
    # Retrieve visit count from session
    visits = int(get_server_side_cookie(request, 'visits', '1'))

    # Retrieve last visit timestamp from session
    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    # If it's been more than a day since last visit, increment the visit count
    if (datetime.now() - last_visit_time).days > 0:
        visits += 1
        request.session['last_visit'] = str(datetime.now())  # Update last visit
    else:
        request.session['last_visit'] = last_visit_cookie  # Keep previous timestamp

    # Update visits count in session
    request.session['visits'] = visits

tango_with_django_project/rango/templates/rango/about.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}About Rango{% endblock %}

{% block body_block %}
    <h1>About Rango</h1>
    <p>Welcome to the About Page.</p>
    <p><strong>Visits:</strong> {{ visits }}</p>  <!-- Display visit count -->
{% endblock %}

{% block body_block %}
    <h1>Rango says...</h1>
    <p>Here is the about page.</p>

    <!-- Static Image -->
    <img src="{% static 'images/rango.jpg' %}" alt="Rango Image">

    <p>This tutorial has been put together by <strong>Your Name</strong>.</p>

    <!-- Media Image -->
    <img src="/media/cat.jpg" alt="Picture of a Cat">
{% endblock %}

tango_with_django_project/rango/templates/rango/add_category.html
{% extends 'rango/base.html' %}

{% block title_block %}Add a Category{% endblock %}

{% block body_block %}
    <h1>Add a New Category</h1>
    <form method="post" action="{% url 'rango:add_category' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add Category">
    </form>
{% endblock %}

tango_with_django_project/rango/templates/rango/add_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Page</title>
</head>

{% extends 'rango/base.html' %}
{% block title_block %}
    Add a Page
{% endblock %}

{% block body_block %}
    <h1>Add a Page to {{ category.name }}</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit" value="Add Page" />
    </form>

    <a href="{% url 'rango:show_category' category.slug %}">Back to {{ category.name }}</a>
{% endblock %}

<body>
    <h1>Add a New Page to {{ category.name }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add Page">
    </form>
    <a href="{% url 'show_category' category.slug %}">Back to Category</a>
</body>
</html>

tango_with_django_project/rango/templates/rango/base.html
<!DOCTYPE html>
{% load static %}
{% load rango_template_tags %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Rango - {% block title_block %}{% endblock %}</title>
    <title>
        Rango -
        {% block title_block %}
            How to Tango with Django!
        {% endblock %}
    </title>
</head>
<body>
    <header>
        <h1>Welcome to Rango</h1>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                    <!-- Show these links when the user is logged in -->
                    <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
                    <li><a href="{% url 'rango:logout' %}">Logout</a></li>
                {% else %}
                    <!-- Show these links when the user is NOT logged in -->
                    <li><a href="{% url 'rango:register' %}">Sign Up</a></li>
                    <li><a href="{% url 'rango:login' %}">Login</a></li>
                {% endif %}

                <!-- Always visible -->
                <li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>
                <li><a href="{% url 'rango:about' %}">About</a></li>
                <li><a href="{% url 'rango:index' %}">Index</a></li>
            </ul>
        </nav>
    </header>

    <div>
        <a href="{% url 'rango:index' %}">Home</a>
        <a href="{% url 'about' %}">About</a>
        <a href="{% url 'add_category' %}">Add Category</a>

        {% if user.is_authenticated %}
            <a href="{% url 'add_category' %}">Add Category</a>
            <a href="{% url 'logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'login' %}">Login</a>
        {% endif %}
    </div>

    <div>
    {% block sidebar_block %}
        {% get_category_list category %}
    {% endblock %}
    </div>

    <hr>

    <main>
        {% block body_block %}
        {% endblock %}
    </main>

    </hr>

    <footer>
        <p>&copy; 2025 Rango - A Django Learning App</p>
    </footer>
</body>
</html>

tango_with_django_project/rango/templates/rango/categories.html
<ul>
    {% if categories %}
        {% for c in categories %}
            {% if c == current_category %}
                <li><strong><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></strong></li>
            {% else %}
                <li><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></li>
            {% endif %}
        {% endfor %}
    {% else %}
        <li><strong>No categories available.</strong></li>
    {% endif %}
</ul>

tango_with_django_project/rango/templates/rango/category.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    {% if category %}{{ category.name }}{% else %}Unknown Category{% endif %}
{% endblock %}

{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if category %}
        <h1>{{ category.name }}</h1>
        <h2>Pages</h2>
        {% if pages %}
        <ul>
            {% for page in pages %}
                <li><a href="{{ page.url }}">{{ page.title }}</a></li>
            {% empty %}
                <li><strong>No pages in this category.</strong></li>
            {% endfor %}
        </ul>
        {% else %}
            <h1>Unknown Category</h1>
            <p>The category you are looking for does not exist.</p>
        {% endif %}

        {% if user.is_authenticated %}
            <a href="{% url 'add_page' category.slug %}">Add a New Page</a>
        {% endif %}

        <a href="{% url 'rango:add_page' category.slug %}">Add Page</a> <br />
    {% else %}
        <p>The specified category does not exist.</p>
    {% endif %}
{% endblock %}

tango_with_django_project/rango/templates/rango/index.html
{% extends 'rango/base.html' %}
{% load static %}
{% block title_block %}Homepage{% endblock %}

{% block body_block %}
    <h1>Welcome to Rango!</h1>
    <p>Crunchy, creamy, cookie, candy, cupcake!</p>
    <h2>Most Liked Categories</h2>
    <ul>
        {% for category in categories %}
            <li><a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a></li>
        {% empty %}
            <li><strong>No categories available.</strong></li>
        {% endfor %}
    </ul>

    <h2>Most Viewed Pages</h2>
    <ul>
            {% for page in pages %}
                <li><a href="{{ page.url }}">{{ page.title }}</a> - {{ page.views }} views</li>
            {% empty %}
                <li><strong>There are no pages present.</strong></li>
            {% endfor %}
    </ul>

    <p><strong>Visits: {{ visits }}</strong></p>

{% endblock %}

{% if user.is_authenticated %}
    <p>Howdy, {{ user.username }}!</p>
{% else %}
    <p>Hey there partner!</p>
{% endif %}

tango_with_django_project/rango/templates/rango/login.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
    <h1>Login to Rango</h1>
    <form id="login_form" method="post" action="{% url 'rango:login' %}">
        {% csrf_token %}
        Username: <input type="text" name="username" size="50"><br>
        Password: <input type="password" name="password" size="50"><br>
        <input type="submit" value="Login">
    </form>
{% endblock %}

tango_with_django_project/rango/templates/rango/register.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
    <h1>Register for Rango</h1>
    {% if registered %}
        <p>Rango says: <strong>Thank you for registering!</strong></p>
        <a href="{% url 'rango:index' %}">Return to the homepage.</a>
    {% else %}
        <p>Rango says: <strong>Register here!</strong></p>
        <form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" name="submit" value="Register">
        </form>
    {% endif %}
{% endblock %}

tango_with_django_project/rango/templates/rango/restricted.html
{% extends 'rango/base.html' %}

{% block title_block %}Restricted Page{% endblock %}

{% block body_block %}
    <h1>Restricted Access</h1>
    <p>Sorry, you must be logged in to view this page.</p>
{% endblock %}